# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6be0b8fb0e388396a01d73a768ca79a1227b4c18788546f4c7fa7b0b5cc2479865ede6f04a6db5b2ec5d4da556d95438bafc6ca925e111e6722eeed308951e50

test:
  secret_key_base: 49d5881b4d407812245bbbb5eb614502e2979c6b6285e82695fbffbf71e88a86547c82d09c345c09996bdbe3792ad8a57c7ea2ea5812194a99d8cda4c5027e6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
